default: &default
  adapter: postgresql
  host:     <%= ImmobilienScout.configuration.database_host %>
  username: <%= ImmobilienScout.configuration.database_username %>
  password: <%= ImmobilienScout.configuration.database_password %>
  # pool: 5

development:
  <<: *default
  database: <%= ImmobilienScout.configuration.database_name + '_development' %>

test:
  <<: *default
  database: <%= ImmobilienScout.configuration.database_name + '_test' %>

production:
  <<: *default
  database: <%= ImmobilienScout.configuration.database_name %>